version: "3"
services:
  api:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - "8082:8081"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env.development
    depends_on:
      - db
    command: npm run dev

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080